# Generated by Django 5.1.2 on 2024-10-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
